// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.28.3

package com.nodiumhosting.vaultmapper.proto;

public interface ColorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Color)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 r = 1;</code>
   * @return The r.
   */
  int getR();

  /**
   * <code>uint32 g = 2;</code>
   * @return The g.
   */
  int getG();

  /**
   * <code>uint32 b = 3;</code>
   * @return The b.
   */
  int getB();
}
