// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.29.1

package com.nodiumhosting.vaultmapper.proto;

/**
 * Protobuf type {@code Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Message.class.getName());
  }
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    type_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nodiumhosting.vaultmapper.proto.Message.class, com.nodiumhosting.vaultmapper.proto.Message.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.MessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.nodiumhosting.vaultmapper.proto.MessageType getType() {
    com.nodiumhosting.vaultmapper.proto.MessageType result = com.nodiumhosting.vaultmapper.proto.MessageType.forNumber(type_);
    return result == null ? com.nodiumhosting.vaultmapper.proto.MessageType.UNRECOGNIZED : result;
  }

  public static final int VAULT_FIELD_NUMBER = 2;
  private com.nodiumhosting.vaultmapper.proto.Vault vault_;
  /**
   * <pre>
   * ditched oneof because protoc refused to generate it properly
   * </pre>
   *
   * <code>.Vault vault = 2;</code>
   * @return Whether the vault field is set.
   */
  @java.lang.Override
  public boolean hasVault() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * ditched oneof because protoc refused to generate it properly
   * </pre>
   *
   * <code>.Vault vault = 2;</code>
   * @return The vault.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.Vault getVault() {
    return vault_ == null ? com.nodiumhosting.vaultmapper.proto.Vault.getDefaultInstance() : vault_;
  }
  /**
   * <pre>
   * ditched oneof because protoc refused to generate it properly
   * </pre>
   *
   * <code>.Vault vault = 2;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultOrBuilder getVaultOrBuilder() {
    return vault_ == null ? com.nodiumhosting.vaultmapper.proto.Vault.getDefaultInstance() : vault_;
  }

  public static final int VAULTPLAYER_FIELD_NUMBER = 3;
  private com.nodiumhosting.vaultmapper.proto.VaultPlayer vaultPlayer_;
  /**
   * <code>.VaultPlayer vaultPlayer = 3;</code>
   * @return Whether the vaultPlayer field is set.
   */
  @java.lang.Override
  public boolean hasVaultPlayer() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.VaultPlayer vaultPlayer = 3;</code>
   * @return The vaultPlayer.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultPlayer getVaultPlayer() {
    return vaultPlayer_ == null ? com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance() : vaultPlayer_;
  }
  /**
   * <code>.VaultPlayer vaultPlayer = 3;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder getVaultPlayerOrBuilder() {
    return vaultPlayer_ == null ? com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance() : vaultPlayer_;
  }

  public static final int VAULTCELL_FIELD_NUMBER = 4;
  private com.nodiumhosting.vaultmapper.proto.VaultCell vaultCell_;
  /**
   * <code>.VaultCell vaultCell = 4;</code>
   * @return Whether the vaultCell field is set.
   */
  @java.lang.Override
  public boolean hasVaultCell() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.VaultCell vaultCell = 4;</code>
   * @return The vaultCell.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultCell getVaultCell() {
    return vaultCell_ == null ? com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance() : vaultCell_;
  }
  /**
   * <code>.VaultCell vaultCell = 4;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder getVaultCellOrBuilder() {
    return vaultCell_ == null ? com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance() : vaultCell_;
  }

  public static final int PLAYERDISCONNECT_FIELD_NUMBER = 5;
  private com.nodiumhosting.vaultmapper.proto.PlayerDisconnect playerDisconnect_;
  /**
   * <code>.PlayerDisconnect playerDisconnect = 5;</code>
   * @return Whether the playerDisconnect field is set.
   */
  @java.lang.Override
  public boolean hasPlayerDisconnect() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.PlayerDisconnect playerDisconnect = 5;</code>
   * @return The playerDisconnect.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.PlayerDisconnect getPlayerDisconnect() {
    return playerDisconnect_ == null ? com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.getDefaultInstance() : playerDisconnect_;
  }
  /**
   * <code>.PlayerDisconnect playerDisconnect = 5;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.PlayerDisconnectOrBuilder getPlayerDisconnectOrBuilder() {
    return playerDisconnect_ == null ? com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.getDefaultInstance() : playerDisconnect_;
  }

  public static final int TOAST_FIELD_NUMBER = 6;
  private com.nodiumhosting.vaultmapper.proto.Toast toast_;
  /**
   * <code>.Toast toast = 6;</code>
   * @return Whether the toast field is set.
   */
  @java.lang.Override
  public boolean hasToast() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.Toast toast = 6;</code>
   * @return The toast.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.Toast getToast() {
    return toast_ == null ? com.nodiumhosting.vaultmapper.proto.Toast.getDefaultInstance() : toast_;
  }
  /**
   * <code>.Toast toast = 6;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.ToastOrBuilder getToastOrBuilder() {
    return toast_ == null ? com.nodiumhosting.vaultmapper.proto.Toast.getDefaultInstance() : toast_;
  }

  public static final int VIEWERCODEREQUEST_FIELD_NUMBER = 7;
  private com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest viewerCodeRequest_;
  /**
   * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
   * @return Whether the viewerCodeRequest field is set.
   */
  @java.lang.Override
  public boolean hasViewerCodeRequest() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
   * @return The viewerCodeRequest.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest getViewerCodeRequest() {
    return viewerCodeRequest_ == null ? com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.getDefaultInstance() : viewerCodeRequest_;
  }
  /**
   * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.ViewerCodeRequestOrBuilder getViewerCodeRequestOrBuilder() {
    return viewerCodeRequest_ == null ? com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.getDefaultInstance() : viewerCodeRequest_;
  }

  public static final int VIEWERCODE_FIELD_NUMBER = 8;
  private com.nodiumhosting.vaultmapper.proto.ViewerCode viewerCode_;
  /**
   * <code>.ViewerCode viewerCode = 8;</code>
   * @return Whether the viewerCode field is set.
   */
  @java.lang.Override
  public boolean hasViewerCode() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.ViewerCode viewerCode = 8;</code>
   * @return The viewerCode.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.ViewerCode getViewerCode() {
    return viewerCode_ == null ? com.nodiumhosting.vaultmapper.proto.ViewerCode.getDefaultInstance() : viewerCode_;
  }
  /**
   * <code>.ViewerCode viewerCode = 8;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.ViewerCodeOrBuilder getViewerCodeOrBuilder() {
    return viewerCode_ == null ? com.nodiumhosting.vaultmapper.proto.ViewerCode.getDefaultInstance() : viewerCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.nodiumhosting.vaultmapper.proto.MessageType.VAULT.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getVault());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getVaultPlayer());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getVaultCell());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(5, getPlayerDisconnect());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(6, getToast());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(7, getViewerCodeRequest());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(8, getViewerCode());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.nodiumhosting.vaultmapper.proto.MessageType.VAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getVault());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getVaultPlayer());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getVaultCell());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPlayerDisconnect());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getToast());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getViewerCodeRequest());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getViewerCode());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nodiumhosting.vaultmapper.proto.Message)) {
      return super.equals(obj);
    }
    com.nodiumhosting.vaultmapper.proto.Message other = (com.nodiumhosting.vaultmapper.proto.Message) obj;

    if (type_ != other.type_) return false;
    if (hasVault() != other.hasVault()) return false;
    if (hasVault()) {
      if (!getVault()
          .equals(other.getVault())) return false;
    }
    if (hasVaultPlayer() != other.hasVaultPlayer()) return false;
    if (hasVaultPlayer()) {
      if (!getVaultPlayer()
          .equals(other.getVaultPlayer())) return false;
    }
    if (hasVaultCell() != other.hasVaultCell()) return false;
    if (hasVaultCell()) {
      if (!getVaultCell()
          .equals(other.getVaultCell())) return false;
    }
    if (hasPlayerDisconnect() != other.hasPlayerDisconnect()) return false;
    if (hasPlayerDisconnect()) {
      if (!getPlayerDisconnect()
          .equals(other.getPlayerDisconnect())) return false;
    }
    if (hasToast() != other.hasToast()) return false;
    if (hasToast()) {
      if (!getToast()
          .equals(other.getToast())) return false;
    }
    if (hasViewerCodeRequest() != other.hasViewerCodeRequest()) return false;
    if (hasViewerCodeRequest()) {
      if (!getViewerCodeRequest()
          .equals(other.getViewerCodeRequest())) return false;
    }
    if (hasViewerCode() != other.hasViewerCode()) return false;
    if (hasViewerCode()) {
      if (!getViewerCode()
          .equals(other.getViewerCode())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasVault()) {
      hash = (37 * hash) + VAULT_FIELD_NUMBER;
      hash = (53 * hash) + getVault().hashCode();
    }
    if (hasVaultPlayer()) {
      hash = (37 * hash) + VAULTPLAYER_FIELD_NUMBER;
      hash = (53 * hash) + getVaultPlayer().hashCode();
    }
    if (hasVaultCell()) {
      hash = (37 * hash) + VAULTCELL_FIELD_NUMBER;
      hash = (53 * hash) + getVaultCell().hashCode();
    }
    if (hasPlayerDisconnect()) {
      hash = (37 * hash) + PLAYERDISCONNECT_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerDisconnect().hashCode();
    }
    if (hasToast()) {
      hash = (37 * hash) + TOAST_FIELD_NUMBER;
      hash = (53 * hash) + getToast().hashCode();
    }
    if (hasViewerCodeRequest()) {
      hash = (37 * hash) + VIEWERCODEREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getViewerCodeRequest().hashCode();
    }
    if (hasViewerCode()) {
      hash = (37 * hash) + VIEWERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getViewerCode().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nodiumhosting.vaultmapper.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nodiumhosting.vaultmapper.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nodiumhosting.vaultmapper.proto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message)
      com.nodiumhosting.vaultmapper.proto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nodiumhosting.vaultmapper.proto.Message.class, com.nodiumhosting.vaultmapper.proto.Message.Builder.class);
    }

    // Construct using com.nodiumhosting.vaultmapper.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getVaultFieldBuilder();
        getVaultPlayerFieldBuilder();
        getVaultCellFieldBuilder();
        getPlayerDisconnectFieldBuilder();
        getToastFieldBuilder();
        getViewerCodeRequestFieldBuilder();
        getViewerCodeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      vault_ = null;
      if (vaultBuilder_ != null) {
        vaultBuilder_.dispose();
        vaultBuilder_ = null;
      }
      vaultPlayer_ = null;
      if (vaultPlayerBuilder_ != null) {
        vaultPlayerBuilder_.dispose();
        vaultPlayerBuilder_ = null;
      }
      vaultCell_ = null;
      if (vaultCellBuilder_ != null) {
        vaultCellBuilder_.dispose();
        vaultCellBuilder_ = null;
      }
      playerDisconnect_ = null;
      if (playerDisconnectBuilder_ != null) {
        playerDisconnectBuilder_.dispose();
        playerDisconnectBuilder_ = null;
      }
      toast_ = null;
      if (toastBuilder_ != null) {
        toastBuilder_.dispose();
        toastBuilder_ = null;
      }
      viewerCodeRequest_ = null;
      if (viewerCodeRequestBuilder_ != null) {
        viewerCodeRequestBuilder_.dispose();
        viewerCodeRequestBuilder_ = null;
      }
      viewerCode_ = null;
      if (viewerCodeBuilder_ != null) {
        viewerCodeBuilder_.dispose();
        viewerCodeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Message_descriptor;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.Message getDefaultInstanceForType() {
      return com.nodiumhosting.vaultmapper.proto.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.Message build() {
      com.nodiumhosting.vaultmapper.proto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.Message buildPartial() {
      com.nodiumhosting.vaultmapper.proto.Message result = new com.nodiumhosting.vaultmapper.proto.Message(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nodiumhosting.vaultmapper.proto.Message result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.vault_ = vaultBuilder_ == null
            ? vault_
            : vaultBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.vaultPlayer_ = vaultPlayerBuilder_ == null
            ? vaultPlayer_
            : vaultPlayerBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.vaultCell_ = vaultCellBuilder_ == null
            ? vaultCell_
            : vaultCellBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.playerDisconnect_ = playerDisconnectBuilder_ == null
            ? playerDisconnect_
            : playerDisconnectBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.toast_ = toastBuilder_ == null
            ? toast_
            : toastBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.viewerCodeRequest_ = viewerCodeRequestBuilder_ == null
            ? viewerCodeRequest_
            : viewerCodeRequestBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.viewerCode_ = viewerCodeBuilder_ == null
            ? viewerCode_
            : viewerCodeBuilder_.build();
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nodiumhosting.vaultmapper.proto.Message) {
        return mergeFrom((com.nodiumhosting.vaultmapper.proto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nodiumhosting.vaultmapper.proto.Message other) {
      if (other == com.nodiumhosting.vaultmapper.proto.Message.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasVault()) {
        mergeVault(other.getVault());
      }
      if (other.hasVaultPlayer()) {
        mergeVaultPlayer(other.getVaultPlayer());
      }
      if (other.hasVaultCell()) {
        mergeVaultCell(other.getVaultCell());
      }
      if (other.hasPlayerDisconnect()) {
        mergePlayerDisconnect(other.getPlayerDisconnect());
      }
      if (other.hasToast()) {
        mergeToast(other.getToast());
      }
      if (other.hasViewerCodeRequest()) {
        mergeViewerCodeRequest(other.getViewerCodeRequest());
      }
      if (other.hasViewerCode()) {
        mergeViewerCode(other.getViewerCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getVaultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getVaultPlayerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getVaultCellFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getPlayerDisconnectFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getToastFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getViewerCodeRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getViewerCodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.MessageType getType() {
      com.nodiumhosting.vaultmapper.proto.MessageType result = com.nodiumhosting.vaultmapper.proto.MessageType.forNumber(type_);
      return result == null ? com.nodiumhosting.vaultmapper.proto.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.nodiumhosting.vaultmapper.proto.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.nodiumhosting.vaultmapper.proto.Vault vault_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.Vault, com.nodiumhosting.vaultmapper.proto.Vault.Builder, com.nodiumhosting.vaultmapper.proto.VaultOrBuilder> vaultBuilder_;
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     * @return Whether the vault field is set.
     */
    public boolean hasVault() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     * @return The vault.
     */
    public com.nodiumhosting.vaultmapper.proto.Vault getVault() {
      if (vaultBuilder_ == null) {
        return vault_ == null ? com.nodiumhosting.vaultmapper.proto.Vault.getDefaultInstance() : vault_;
      } else {
        return vaultBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     */
    public Builder setVault(com.nodiumhosting.vaultmapper.proto.Vault value) {
      if (vaultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vault_ = value;
      } else {
        vaultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     */
    public Builder setVault(
        com.nodiumhosting.vaultmapper.proto.Vault.Builder builderForValue) {
      if (vaultBuilder_ == null) {
        vault_ = builderForValue.build();
      } else {
        vaultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     */
    public Builder mergeVault(com.nodiumhosting.vaultmapper.proto.Vault value) {
      if (vaultBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          vault_ != null &&
          vault_ != com.nodiumhosting.vaultmapper.proto.Vault.getDefaultInstance()) {
          getVaultBuilder().mergeFrom(value);
        } else {
          vault_ = value;
        }
      } else {
        vaultBuilder_.mergeFrom(value);
      }
      if (vault_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     */
    public Builder clearVault() {
      bitField0_ = (bitField0_ & ~0x00000002);
      vault_ = null;
      if (vaultBuilder_ != null) {
        vaultBuilder_.dispose();
        vaultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.Vault.Builder getVaultBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getVaultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultOrBuilder getVaultOrBuilder() {
      if (vaultBuilder_ != null) {
        return vaultBuilder_.getMessageOrBuilder();
      } else {
        return vault_ == null ?
            com.nodiumhosting.vaultmapper.proto.Vault.getDefaultInstance() : vault_;
      }
    }
    /**
     * <pre>
     * ditched oneof because protoc refused to generate it properly
     * </pre>
     *
     * <code>.Vault vault = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.Vault, com.nodiumhosting.vaultmapper.proto.Vault.Builder, com.nodiumhosting.vaultmapper.proto.VaultOrBuilder> 
        getVaultFieldBuilder() {
      if (vaultBuilder_ == null) {
        vaultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.Vault, com.nodiumhosting.vaultmapper.proto.Vault.Builder, com.nodiumhosting.vaultmapper.proto.VaultOrBuilder>(
                getVault(),
                getParentForChildren(),
                isClean());
        vault_ = null;
      }
      return vaultBuilder_;
    }

    private com.nodiumhosting.vaultmapper.proto.VaultPlayer vaultPlayer_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultPlayer, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder, com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder> vaultPlayerBuilder_;
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     * @return Whether the vaultPlayer field is set.
     */
    public boolean hasVaultPlayer() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     * @return The vaultPlayer.
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer getVaultPlayer() {
      if (vaultPlayerBuilder_ == null) {
        return vaultPlayer_ == null ? com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance() : vaultPlayer_;
      } else {
        return vaultPlayerBuilder_.getMessage();
      }
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     */
    public Builder setVaultPlayer(com.nodiumhosting.vaultmapper.proto.VaultPlayer value) {
      if (vaultPlayerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vaultPlayer_ = value;
      } else {
        vaultPlayerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     */
    public Builder setVaultPlayer(
        com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder builderForValue) {
      if (vaultPlayerBuilder_ == null) {
        vaultPlayer_ = builderForValue.build();
      } else {
        vaultPlayerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     */
    public Builder mergeVaultPlayer(com.nodiumhosting.vaultmapper.proto.VaultPlayer value) {
      if (vaultPlayerBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          vaultPlayer_ != null &&
          vaultPlayer_ != com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance()) {
          getVaultPlayerBuilder().mergeFrom(value);
        } else {
          vaultPlayer_ = value;
        }
      } else {
        vaultPlayerBuilder_.mergeFrom(value);
      }
      if (vaultPlayer_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     */
    public Builder clearVaultPlayer() {
      bitField0_ = (bitField0_ & ~0x00000004);
      vaultPlayer_ = null;
      if (vaultPlayerBuilder_ != null) {
        vaultPlayerBuilder_.dispose();
        vaultPlayerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder getVaultPlayerBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getVaultPlayerFieldBuilder().getBuilder();
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder getVaultPlayerOrBuilder() {
      if (vaultPlayerBuilder_ != null) {
        return vaultPlayerBuilder_.getMessageOrBuilder();
      } else {
        return vaultPlayer_ == null ?
            com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance() : vaultPlayer_;
      }
    }
    /**
     * <code>.VaultPlayer vaultPlayer = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultPlayer, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder, com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder> 
        getVaultPlayerFieldBuilder() {
      if (vaultPlayerBuilder_ == null) {
        vaultPlayerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.VaultPlayer, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder, com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder>(
                getVaultPlayer(),
                getParentForChildren(),
                isClean());
        vaultPlayer_ = null;
      }
      return vaultPlayerBuilder_;
    }

    private com.nodiumhosting.vaultmapper.proto.VaultCell vaultCell_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultCell, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder, com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder> vaultCellBuilder_;
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     * @return Whether the vaultCell field is set.
     */
    public boolean hasVaultCell() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     * @return The vaultCell.
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCell getVaultCell() {
      if (vaultCellBuilder_ == null) {
        return vaultCell_ == null ? com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance() : vaultCell_;
      } else {
        return vaultCellBuilder_.getMessage();
      }
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     */
    public Builder setVaultCell(com.nodiumhosting.vaultmapper.proto.VaultCell value) {
      if (vaultCellBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vaultCell_ = value;
      } else {
        vaultCellBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     */
    public Builder setVaultCell(
        com.nodiumhosting.vaultmapper.proto.VaultCell.Builder builderForValue) {
      if (vaultCellBuilder_ == null) {
        vaultCell_ = builderForValue.build();
      } else {
        vaultCellBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     */
    public Builder mergeVaultCell(com.nodiumhosting.vaultmapper.proto.VaultCell value) {
      if (vaultCellBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          vaultCell_ != null &&
          vaultCell_ != com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance()) {
          getVaultCellBuilder().mergeFrom(value);
        } else {
          vaultCell_ = value;
        }
      } else {
        vaultCellBuilder_.mergeFrom(value);
      }
      if (vaultCell_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     */
    public Builder clearVaultCell() {
      bitField0_ = (bitField0_ & ~0x00000008);
      vaultCell_ = null;
      if (vaultCellBuilder_ != null) {
        vaultCellBuilder_.dispose();
        vaultCellBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCell.Builder getVaultCellBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getVaultCellFieldBuilder().getBuilder();
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder getVaultCellOrBuilder() {
      if (vaultCellBuilder_ != null) {
        return vaultCellBuilder_.getMessageOrBuilder();
      } else {
        return vaultCell_ == null ?
            com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance() : vaultCell_;
      }
    }
    /**
     * <code>.VaultCell vaultCell = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultCell, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder, com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder> 
        getVaultCellFieldBuilder() {
      if (vaultCellBuilder_ == null) {
        vaultCellBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.VaultCell, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder, com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder>(
                getVaultCell(),
                getParentForChildren(),
                isClean());
        vaultCell_ = null;
      }
      return vaultCellBuilder_;
    }

    private com.nodiumhosting.vaultmapper.proto.PlayerDisconnect playerDisconnect_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.PlayerDisconnect, com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.Builder, com.nodiumhosting.vaultmapper.proto.PlayerDisconnectOrBuilder> playerDisconnectBuilder_;
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     * @return Whether the playerDisconnect field is set.
     */
    public boolean hasPlayerDisconnect() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     * @return The playerDisconnect.
     */
    public com.nodiumhosting.vaultmapper.proto.PlayerDisconnect getPlayerDisconnect() {
      if (playerDisconnectBuilder_ == null) {
        return playerDisconnect_ == null ? com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.getDefaultInstance() : playerDisconnect_;
      } else {
        return playerDisconnectBuilder_.getMessage();
      }
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     */
    public Builder setPlayerDisconnect(com.nodiumhosting.vaultmapper.proto.PlayerDisconnect value) {
      if (playerDisconnectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playerDisconnect_ = value;
      } else {
        playerDisconnectBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     */
    public Builder setPlayerDisconnect(
        com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.Builder builderForValue) {
      if (playerDisconnectBuilder_ == null) {
        playerDisconnect_ = builderForValue.build();
      } else {
        playerDisconnectBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     */
    public Builder mergePlayerDisconnect(com.nodiumhosting.vaultmapper.proto.PlayerDisconnect value) {
      if (playerDisconnectBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          playerDisconnect_ != null &&
          playerDisconnect_ != com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.getDefaultInstance()) {
          getPlayerDisconnectBuilder().mergeFrom(value);
        } else {
          playerDisconnect_ = value;
        }
      } else {
        playerDisconnectBuilder_.mergeFrom(value);
      }
      if (playerDisconnect_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     */
    public Builder clearPlayerDisconnect() {
      bitField0_ = (bitField0_ & ~0x00000010);
      playerDisconnect_ = null;
      if (playerDisconnectBuilder_ != null) {
        playerDisconnectBuilder_.dispose();
        playerDisconnectBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.Builder getPlayerDisconnectBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getPlayerDisconnectFieldBuilder().getBuilder();
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.PlayerDisconnectOrBuilder getPlayerDisconnectOrBuilder() {
      if (playerDisconnectBuilder_ != null) {
        return playerDisconnectBuilder_.getMessageOrBuilder();
      } else {
        return playerDisconnect_ == null ?
            com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.getDefaultInstance() : playerDisconnect_;
      }
    }
    /**
     * <code>.PlayerDisconnect playerDisconnect = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.PlayerDisconnect, com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.Builder, com.nodiumhosting.vaultmapper.proto.PlayerDisconnectOrBuilder> 
        getPlayerDisconnectFieldBuilder() {
      if (playerDisconnectBuilder_ == null) {
        playerDisconnectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.PlayerDisconnect, com.nodiumhosting.vaultmapper.proto.PlayerDisconnect.Builder, com.nodiumhosting.vaultmapper.proto.PlayerDisconnectOrBuilder>(
                getPlayerDisconnect(),
                getParentForChildren(),
                isClean());
        playerDisconnect_ = null;
      }
      return playerDisconnectBuilder_;
    }

    private com.nodiumhosting.vaultmapper.proto.Toast toast_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.Toast, com.nodiumhosting.vaultmapper.proto.Toast.Builder, com.nodiumhosting.vaultmapper.proto.ToastOrBuilder> toastBuilder_;
    /**
     * <code>.Toast toast = 6;</code>
     * @return Whether the toast field is set.
     */
    public boolean hasToast() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.Toast toast = 6;</code>
     * @return The toast.
     */
    public com.nodiumhosting.vaultmapper.proto.Toast getToast() {
      if (toastBuilder_ == null) {
        return toast_ == null ? com.nodiumhosting.vaultmapper.proto.Toast.getDefaultInstance() : toast_;
      } else {
        return toastBuilder_.getMessage();
      }
    }
    /**
     * <code>.Toast toast = 6;</code>
     */
    public Builder setToast(com.nodiumhosting.vaultmapper.proto.Toast value) {
      if (toastBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toast_ = value;
      } else {
        toastBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Toast toast = 6;</code>
     */
    public Builder setToast(
        com.nodiumhosting.vaultmapper.proto.Toast.Builder builderForValue) {
      if (toastBuilder_ == null) {
        toast_ = builderForValue.build();
      } else {
        toastBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Toast toast = 6;</code>
     */
    public Builder mergeToast(com.nodiumhosting.vaultmapper.proto.Toast value) {
      if (toastBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          toast_ != null &&
          toast_ != com.nodiumhosting.vaultmapper.proto.Toast.getDefaultInstance()) {
          getToastBuilder().mergeFrom(value);
        } else {
          toast_ = value;
        }
      } else {
        toastBuilder_.mergeFrom(value);
      }
      if (toast_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Toast toast = 6;</code>
     */
    public Builder clearToast() {
      bitField0_ = (bitField0_ & ~0x00000020);
      toast_ = null;
      if (toastBuilder_ != null) {
        toastBuilder_.dispose();
        toastBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Toast toast = 6;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.Toast.Builder getToastBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getToastFieldBuilder().getBuilder();
    }
    /**
     * <code>.Toast toast = 6;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.ToastOrBuilder getToastOrBuilder() {
      if (toastBuilder_ != null) {
        return toastBuilder_.getMessageOrBuilder();
      } else {
        return toast_ == null ?
            com.nodiumhosting.vaultmapper.proto.Toast.getDefaultInstance() : toast_;
      }
    }
    /**
     * <code>.Toast toast = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.Toast, com.nodiumhosting.vaultmapper.proto.Toast.Builder, com.nodiumhosting.vaultmapper.proto.ToastOrBuilder> 
        getToastFieldBuilder() {
      if (toastBuilder_ == null) {
        toastBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.Toast, com.nodiumhosting.vaultmapper.proto.Toast.Builder, com.nodiumhosting.vaultmapper.proto.ToastOrBuilder>(
                getToast(),
                getParentForChildren(),
                isClean());
        toast_ = null;
      }
      return toastBuilder_;
    }

    private com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest viewerCodeRequest_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest, com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.Builder, com.nodiumhosting.vaultmapper.proto.ViewerCodeRequestOrBuilder> viewerCodeRequestBuilder_;
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     * @return Whether the viewerCodeRequest field is set.
     */
    public boolean hasViewerCodeRequest() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     * @return The viewerCodeRequest.
     */
    public com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest getViewerCodeRequest() {
      if (viewerCodeRequestBuilder_ == null) {
        return viewerCodeRequest_ == null ? com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.getDefaultInstance() : viewerCodeRequest_;
      } else {
        return viewerCodeRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     */
    public Builder setViewerCodeRequest(com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest value) {
      if (viewerCodeRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        viewerCodeRequest_ = value;
      } else {
        viewerCodeRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     */
    public Builder setViewerCodeRequest(
        com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.Builder builderForValue) {
      if (viewerCodeRequestBuilder_ == null) {
        viewerCodeRequest_ = builderForValue.build();
      } else {
        viewerCodeRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     */
    public Builder mergeViewerCodeRequest(com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest value) {
      if (viewerCodeRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          viewerCodeRequest_ != null &&
          viewerCodeRequest_ != com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.getDefaultInstance()) {
          getViewerCodeRequestBuilder().mergeFrom(value);
        } else {
          viewerCodeRequest_ = value;
        }
      } else {
        viewerCodeRequestBuilder_.mergeFrom(value);
      }
      if (viewerCodeRequest_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     */
    public Builder clearViewerCodeRequest() {
      bitField0_ = (bitField0_ & ~0x00000040);
      viewerCodeRequest_ = null;
      if (viewerCodeRequestBuilder_ != null) {
        viewerCodeRequestBuilder_.dispose();
        viewerCodeRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.Builder getViewerCodeRequestBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getViewerCodeRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.ViewerCodeRequestOrBuilder getViewerCodeRequestOrBuilder() {
      if (viewerCodeRequestBuilder_ != null) {
        return viewerCodeRequestBuilder_.getMessageOrBuilder();
      } else {
        return viewerCodeRequest_ == null ?
            com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.getDefaultInstance() : viewerCodeRequest_;
      }
    }
    /**
     * <code>.ViewerCodeRequest viewerCodeRequest = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest, com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.Builder, com.nodiumhosting.vaultmapper.proto.ViewerCodeRequestOrBuilder> 
        getViewerCodeRequestFieldBuilder() {
      if (viewerCodeRequestBuilder_ == null) {
        viewerCodeRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest, com.nodiumhosting.vaultmapper.proto.ViewerCodeRequest.Builder, com.nodiumhosting.vaultmapper.proto.ViewerCodeRequestOrBuilder>(
                getViewerCodeRequest(),
                getParentForChildren(),
                isClean());
        viewerCodeRequest_ = null;
      }
      return viewerCodeRequestBuilder_;
    }

    private com.nodiumhosting.vaultmapper.proto.ViewerCode viewerCode_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.ViewerCode, com.nodiumhosting.vaultmapper.proto.ViewerCode.Builder, com.nodiumhosting.vaultmapper.proto.ViewerCodeOrBuilder> viewerCodeBuilder_;
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     * @return Whether the viewerCode field is set.
     */
    public boolean hasViewerCode() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     * @return The viewerCode.
     */
    public com.nodiumhosting.vaultmapper.proto.ViewerCode getViewerCode() {
      if (viewerCodeBuilder_ == null) {
        return viewerCode_ == null ? com.nodiumhosting.vaultmapper.proto.ViewerCode.getDefaultInstance() : viewerCode_;
      } else {
        return viewerCodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     */
    public Builder setViewerCode(com.nodiumhosting.vaultmapper.proto.ViewerCode value) {
      if (viewerCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        viewerCode_ = value;
      } else {
        viewerCodeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     */
    public Builder setViewerCode(
        com.nodiumhosting.vaultmapper.proto.ViewerCode.Builder builderForValue) {
      if (viewerCodeBuilder_ == null) {
        viewerCode_ = builderForValue.build();
      } else {
        viewerCodeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     */
    public Builder mergeViewerCode(com.nodiumhosting.vaultmapper.proto.ViewerCode value) {
      if (viewerCodeBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          viewerCode_ != null &&
          viewerCode_ != com.nodiumhosting.vaultmapper.proto.ViewerCode.getDefaultInstance()) {
          getViewerCodeBuilder().mergeFrom(value);
        } else {
          viewerCode_ = value;
        }
      } else {
        viewerCodeBuilder_.mergeFrom(value);
      }
      if (viewerCode_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     */
    public Builder clearViewerCode() {
      bitField0_ = (bitField0_ & ~0x00000080);
      viewerCode_ = null;
      if (viewerCodeBuilder_ != null) {
        viewerCodeBuilder_.dispose();
        viewerCodeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.ViewerCode.Builder getViewerCodeBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getViewerCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.ViewerCodeOrBuilder getViewerCodeOrBuilder() {
      if (viewerCodeBuilder_ != null) {
        return viewerCodeBuilder_.getMessageOrBuilder();
      } else {
        return viewerCode_ == null ?
            com.nodiumhosting.vaultmapper.proto.ViewerCode.getDefaultInstance() : viewerCode_;
      }
    }
    /**
     * <code>.ViewerCode viewerCode = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.ViewerCode, com.nodiumhosting.vaultmapper.proto.ViewerCode.Builder, com.nodiumhosting.vaultmapper.proto.ViewerCodeOrBuilder> 
        getViewerCodeFieldBuilder() {
      if (viewerCodeBuilder_ == null) {
        viewerCodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.ViewerCode, com.nodiumhosting.vaultmapper.proto.ViewerCode.Builder, com.nodiumhosting.vaultmapper.proto.ViewerCodeOrBuilder>(
                getViewerCode(),
                getParentForChildren(),
                isClean());
        viewerCode_ = null;
      }
      return viewerCodeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Message)
  }

  // @@protoc_insertion_point(class_scope:Message)
  private static final com.nodiumhosting.vaultmapper.proto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nodiumhosting.vaultmapper.proto.Message();
  }

  public static com.nodiumhosting.vaultmapper.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

