// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.28.3

package com.nodiumhosting.vaultmapper.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.MessageType type = 1;</code>
   * @return The type.
   */
  com.nodiumhosting.vaultmapper.proto.MessageType getType();

  /**
   * <pre>
   * ditched oneof because protoc refused to generate it properly
   * </pre>
   *
   * <code>.Vault vault = 2;</code>
   * @return Whether the vault field is set.
   */
  boolean hasVault();
  /**
   * <pre>
   * ditched oneof because protoc refused to generate it properly
   * </pre>
   *
   * <code>.Vault vault = 2;</code>
   * @return The vault.
   */
  com.nodiumhosting.vaultmapper.proto.Vault getVault();
  /**
   * <pre>
   * ditched oneof because protoc refused to generate it properly
   * </pre>
   *
   * <code>.Vault vault = 2;</code>
   */
  com.nodiumhosting.vaultmapper.proto.VaultOrBuilder getVaultOrBuilder();

  /**
   * <code>.VaultPlayer vaultPlayer = 3;</code>
   * @return Whether the vaultPlayer field is set.
   */
  boolean hasVaultPlayer();
  /**
   * <code>.VaultPlayer vaultPlayer = 3;</code>
   * @return The vaultPlayer.
   */
  com.nodiumhosting.vaultmapper.proto.VaultPlayer getVaultPlayer();
  /**
   * <code>.VaultPlayer vaultPlayer = 3;</code>
   */
  com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder getVaultPlayerOrBuilder();

  /**
   * <code>.VaultCell vaultCell = 4;</code>
   * @return Whether the vaultCell field is set.
   */
  boolean hasVaultCell();
  /**
   * <code>.VaultCell vaultCell = 4;</code>
   * @return The vaultCell.
   */
  com.nodiumhosting.vaultmapper.proto.VaultCell getVaultCell();
  /**
   * <code>.VaultCell vaultCell = 4;</code>
   */
  com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder getVaultCellOrBuilder();

  /**
   * <code>.PlayerDisconnect playerDisconnect = 5;</code>
   * @return Whether the playerDisconnect field is set.
   */
  boolean hasPlayerDisconnect();
  /**
   * <code>.PlayerDisconnect playerDisconnect = 5;</code>
   * @return The playerDisconnect.
   */
  com.nodiumhosting.vaultmapper.proto.PlayerDisconnect getPlayerDisconnect();
  /**
   * <code>.PlayerDisconnect playerDisconnect = 5;</code>
   */
  com.nodiumhosting.vaultmapper.proto.PlayerDisconnectOrBuilder getPlayerDisconnectOrBuilder();

  /**
   * <code>.Toast toast = 6;</code>
   * @return Whether the toast field is set.
   */
  boolean hasToast();
  /**
   * <code>.Toast toast = 6;</code>
   * @return The toast.
   */
  com.nodiumhosting.vaultmapper.proto.Toast getToast();
  /**
   * <code>.Toast toast = 6;</code>
   */
  com.nodiumhosting.vaultmapper.proto.ToastOrBuilder getToastOrBuilder();
}
