// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.30.1

package com.nodiumhosting.vaultmapper.proto;

/**
 * Protobuf type {@code VaultCell}
 */
public final class VaultCell extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:VaultCell)
    VaultCellOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 1,
      /* suffix= */ "",
      VaultCell.class.getName());
  }
  // Use VaultCell.newBuilder() to construct.
  private VaultCell(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VaultCell() {
    cellType_ = 0;
    roomType_ = 0;
    roomName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultCell_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultCell_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nodiumhosting.vaultmapper.proto.VaultCell.class, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder.class);
  }

  public static final int X_FIELD_NUMBER = 1;
  private int x_ = 0;
  /**
   * <code>sint32 x = 1;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Z_FIELD_NUMBER = 2;
  private int z_ = 0;
  /**
   * <code>sint32 z = 2;</code>
   * @return The z.
   */
  @java.lang.Override
  public int getZ() {
    return z_;
  }

  public static final int CELLTYPE_FIELD_NUMBER = 3;
  private int cellType_ = 0;
  /**
   * <code>.CellType cellType = 3;</code>
   * @return The enum numeric value on the wire for cellType.
   */
  @java.lang.Override public int getCellTypeValue() {
    return cellType_;
  }
  /**
   * <code>.CellType cellType = 3;</code>
   * @return The cellType.
   */
  @java.lang.Override public com.nodiumhosting.vaultmapper.proto.CellType getCellType() {
    com.nodiumhosting.vaultmapper.proto.CellType result = com.nodiumhosting.vaultmapper.proto.CellType.forNumber(cellType_);
    return result == null ? com.nodiumhosting.vaultmapper.proto.CellType.UNRECOGNIZED : result;
  }

  public static final int ROOMTYPE_FIELD_NUMBER = 4;
  private int roomType_ = 0;
  /**
   * <code>.RoomType roomType = 4;</code>
   * @return The enum numeric value on the wire for roomType.
   */
  @java.lang.Override public int getRoomTypeValue() {
    return roomType_;
  }
  /**
   * <code>.RoomType roomType = 4;</code>
   * @return The roomType.
   */
  @java.lang.Override public com.nodiumhosting.vaultmapper.proto.RoomType getRoomType() {
    com.nodiumhosting.vaultmapper.proto.RoomType result = com.nodiumhosting.vaultmapper.proto.RoomType.forNumber(roomType_);
    return result == null ? com.nodiumhosting.vaultmapper.proto.RoomType.UNRECOGNIZED : result;
  }

  public static final int ROOMNAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roomName_ = "";
  /**
   * <code>string roomName = 5;</code>
   * @return The roomName.
   */
  @java.lang.Override
  public java.lang.String getRoomName() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomName_ = s;
      return s;
    }
  }
  /**
   * <code>string roomName = 5;</code>
   * @return The bytes for roomName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomNameBytes() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPLORED_FIELD_NUMBER = 6;
  private boolean explored_ = false;
  /**
   * <code>bool explored = 6;</code>
   * @return The explored.
   */
  @java.lang.Override
  public boolean getExplored() {
    return explored_;
  }

  public static final int INSCRIBED_FIELD_NUMBER = 7;
  private boolean inscribed_ = false;
  /**
   * <code>bool inscribed = 7;</code>
   * @return The inscribed.
   */
  @java.lang.Override
  public boolean getInscribed() {
    return inscribed_;
  }

  public static final int MARKED_FIELD_NUMBER = 8;
  private boolean marked_ = false;
  /**
   * <code>bool marked = 8;</code>
   * @return The marked.
   */
  @java.lang.Override
  public boolean getMarked() {
    return marked_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (x_ != 0) {
      output.writeSInt32(1, x_);
    }
    if (z_ != 0) {
      output.writeSInt32(2, z_);
    }
    if (cellType_ != com.nodiumhosting.vaultmapper.proto.CellType.CELLTYPE_UNKNOWN.getNumber()) {
      output.writeEnum(3, cellType_);
    }
    if (roomType_ != com.nodiumhosting.vaultmapper.proto.RoomType.ROOMTYPE_UNKNOWN.getNumber()) {
      output.writeEnum(4, roomType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(roomName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, roomName_);
    }
    if (explored_ != false) {
      output.writeBool(6, explored_);
    }
    if (inscribed_ != false) {
      output.writeBool(7, inscribed_);
    }
    if (marked_ != false) {
      output.writeBool(8, marked_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, x_);
    }
    if (z_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(2, z_);
    }
    if (cellType_ != com.nodiumhosting.vaultmapper.proto.CellType.CELLTYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, cellType_);
    }
    if (roomType_ != com.nodiumhosting.vaultmapper.proto.RoomType.ROOMTYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, roomType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(roomName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, roomName_);
    }
    if (explored_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, explored_);
    }
    if (inscribed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, inscribed_);
    }
    if (marked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, marked_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nodiumhosting.vaultmapper.proto.VaultCell)) {
      return super.equals(obj);
    }
    com.nodiumhosting.vaultmapper.proto.VaultCell other = (com.nodiumhosting.vaultmapper.proto.VaultCell) obj;

    if (getX()
        != other.getX()) return false;
    if (getZ()
        != other.getZ()) return false;
    if (cellType_ != other.cellType_) return false;
    if (roomType_ != other.roomType_) return false;
    if (!getRoomName()
        .equals(other.getRoomName())) return false;
    if (getExplored()
        != other.getExplored()) return false;
    if (getInscribed()
        != other.getInscribed()) return false;
    if (getMarked()
        != other.getMarked()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Z_FIELD_NUMBER;
    hash = (53 * hash) + getZ();
    hash = (37 * hash) + CELLTYPE_FIELD_NUMBER;
    hash = (53 * hash) + cellType_;
    hash = (37 * hash) + ROOMTYPE_FIELD_NUMBER;
    hash = (53 * hash) + roomType_;
    hash = (37 * hash) + ROOMNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRoomName().hashCode();
    hash = (37 * hash) + EXPLORED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExplored());
    hash = (37 * hash) + INSCRIBED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInscribed());
    hash = (37 * hash) + MARKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMarked());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultCell parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nodiumhosting.vaultmapper.proto.VaultCell prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VaultCell}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VaultCell)
      com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultCell_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultCell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nodiumhosting.vaultmapper.proto.VaultCell.class, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder.class);
    }

    // Construct using com.nodiumhosting.vaultmapper.proto.VaultCell.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      x_ = 0;
      z_ = 0;
      cellType_ = 0;
      roomType_ = 0;
      roomName_ = "";
      explored_ = false;
      inscribed_ = false;
      marked_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultCell_descriptor;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.VaultCell getDefaultInstanceForType() {
      return com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance();
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.VaultCell build() {
      com.nodiumhosting.vaultmapper.proto.VaultCell result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.VaultCell buildPartial() {
      com.nodiumhosting.vaultmapper.proto.VaultCell result = new com.nodiumhosting.vaultmapper.proto.VaultCell(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nodiumhosting.vaultmapper.proto.VaultCell result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.z_ = z_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cellType_ = cellType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.roomType_ = roomType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.roomName_ = roomName_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.explored_ = explored_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.inscribed_ = inscribed_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.marked_ = marked_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nodiumhosting.vaultmapper.proto.VaultCell) {
        return mergeFrom((com.nodiumhosting.vaultmapper.proto.VaultCell)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nodiumhosting.vaultmapper.proto.VaultCell other) {
      if (other == com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance()) return this;
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getZ() != 0) {
        setZ(other.getZ());
      }
      if (other.cellType_ != 0) {
        setCellTypeValue(other.getCellTypeValue());
      }
      if (other.roomType_ != 0) {
        setRoomTypeValue(other.getRoomTypeValue());
      }
      if (!other.getRoomName().isEmpty()) {
        roomName_ = other.roomName_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getExplored() != false) {
        setExplored(other.getExplored());
      }
      if (other.getInscribed() != false) {
        setInscribed(other.getInscribed());
      }
      if (other.getMarked() != false) {
        setMarked(other.getMarked());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              x_ = input.readSInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              z_ = input.readSInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              cellType_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              roomType_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              roomName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              explored_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              inscribed_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              marked_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int x_ ;
    /**
     * <code>sint32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <code>sint32 x = 1;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {

      x_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0;
      onChanged();
      return this;
    }

    private int z_ ;
    /**
     * <code>sint32 z = 2;</code>
     * @return The z.
     */
    @java.lang.Override
    public int getZ() {
      return z_;
    }
    /**
     * <code>sint32 z = 2;</code>
     * @param value The z to set.
     * @return This builder for chaining.
     */
    public Builder setZ(int value) {

      z_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 z = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearZ() {
      bitField0_ = (bitField0_ & ~0x00000002);
      z_ = 0;
      onChanged();
      return this;
    }

    private int cellType_ = 0;
    /**
     * <code>.CellType cellType = 3;</code>
     * @return The enum numeric value on the wire for cellType.
     */
    @java.lang.Override public int getCellTypeValue() {
      return cellType_;
    }
    /**
     * <code>.CellType cellType = 3;</code>
     * @param value The enum numeric value on the wire for cellType to set.
     * @return This builder for chaining.
     */
    public Builder setCellTypeValue(int value) {
      cellType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.CellType cellType = 3;</code>
     * @return The cellType.
     */
    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.CellType getCellType() {
      com.nodiumhosting.vaultmapper.proto.CellType result = com.nodiumhosting.vaultmapper.proto.CellType.forNumber(cellType_);
      return result == null ? com.nodiumhosting.vaultmapper.proto.CellType.UNRECOGNIZED : result;
    }
    /**
     * <code>.CellType cellType = 3;</code>
     * @param value The cellType to set.
     * @return This builder for chaining.
     */
    public Builder setCellType(com.nodiumhosting.vaultmapper.proto.CellType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      cellType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.CellType cellType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCellType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cellType_ = 0;
      onChanged();
      return this;
    }

    private int roomType_ = 0;
    /**
     * <code>.RoomType roomType = 4;</code>
     * @return The enum numeric value on the wire for roomType.
     */
    @java.lang.Override public int getRoomTypeValue() {
      return roomType_;
    }
    /**
     * <code>.RoomType roomType = 4;</code>
     * @param value The enum numeric value on the wire for roomType to set.
     * @return This builder for chaining.
     */
    public Builder setRoomTypeValue(int value) {
      roomType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.RoomType roomType = 4;</code>
     * @return The roomType.
     */
    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.RoomType getRoomType() {
      com.nodiumhosting.vaultmapper.proto.RoomType result = com.nodiumhosting.vaultmapper.proto.RoomType.forNumber(roomType_);
      return result == null ? com.nodiumhosting.vaultmapper.proto.RoomType.UNRECOGNIZED : result;
    }
    /**
     * <code>.RoomType roomType = 4;</code>
     * @param value The roomType to set.
     * @return This builder for chaining.
     */
    public Builder setRoomType(com.nodiumhosting.vaultmapper.proto.RoomType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      roomType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RoomType roomType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      roomType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object roomName_ = "";
    /**
     * <code>string roomName = 5;</code>
     * @return The roomName.
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roomName = 5;</code>
     * @return The bytes for roomName.
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roomName = 5;</code>
     * @param value The roomName to set.
     * @return This builder for chaining.
     */
    public Builder setRoomName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roomName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string roomName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomName() {
      roomName_ = getDefaultInstance().getRoomName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string roomName = 5;</code>
     * @param value The bytes for roomName to set.
     * @return This builder for chaining.
     */
    public Builder setRoomNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roomName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean explored_ ;
    /**
     * <code>bool explored = 6;</code>
     * @return The explored.
     */
    @java.lang.Override
    public boolean getExplored() {
      return explored_;
    }
    /**
     * <code>bool explored = 6;</code>
     * @param value The explored to set.
     * @return This builder for chaining.
     */
    public Builder setExplored(boolean value) {

      explored_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool explored = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearExplored() {
      bitField0_ = (bitField0_ & ~0x00000020);
      explored_ = false;
      onChanged();
      return this;
    }

    private boolean inscribed_ ;
    /**
     * <code>bool inscribed = 7;</code>
     * @return The inscribed.
     */
    @java.lang.Override
    public boolean getInscribed() {
      return inscribed_;
    }
    /**
     * <code>bool inscribed = 7;</code>
     * @param value The inscribed to set.
     * @return This builder for chaining.
     */
    public Builder setInscribed(boolean value) {

      inscribed_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool inscribed = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearInscribed() {
      bitField0_ = (bitField0_ & ~0x00000040);
      inscribed_ = false;
      onChanged();
      return this;
    }

    private boolean marked_ ;
    /**
     * <code>bool marked = 8;</code>
     * @return The marked.
     */
    @java.lang.Override
    public boolean getMarked() {
      return marked_;
    }
    /**
     * <code>bool marked = 8;</code>
     * @param value The marked to set.
     * @return This builder for chaining.
     */
    public Builder setMarked(boolean value) {

      marked_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool marked = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMarked() {
      bitField0_ = (bitField0_ & ~0x00000080);
      marked_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:VaultCell)
  }

  // @@protoc_insertion_point(class_scope:VaultCell)
  private static final com.nodiumhosting.vaultmapper.proto.VaultCell DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nodiumhosting.vaultmapper.proto.VaultCell();
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultCell getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VaultCell>
      PARSER = new com.google.protobuf.AbstractParser<VaultCell>() {
    @java.lang.Override
    public VaultCell parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VaultCell> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VaultCell> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultCell getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

