// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vaultmapper.proto
// Protobuf Java Version: 4.29.1

package com.nodiumhosting.vaultmapper.proto;

public final class VaultMapperProto {
  private VaultMapperProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      VaultMapperProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Toast_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Toast_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ViewerCodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ViewerCodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ViewerCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ViewerCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vault_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Vault_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VaultPlayer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VaultPlayer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Color_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Color_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VaultCell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VaultCell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerDisconnect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerDisconnect_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021vaultmapper.proto\"\222\002\n\007Message\022\032\n\004type\030" +
      "\001 \001(\0162\014.MessageType\022\025\n\005vault\030\002 \001(\0132\006.Vau" +
      "lt\022!\n\013vaultPlayer\030\003 \001(\0132\014.VaultPlayer\022\035\n" +
      "\tvaultCell\030\004 \001(\0132\n.VaultCell\022+\n\020playerDi" +
      "sconnect\030\005 \001(\0132\021.PlayerDisconnect\022\025\n\005toa" +
      "st\030\006 \001(\0132\006.Toast\022-\n\021viewerCodeRequest\030\007 " +
      "\001(\0132\022.ViewerCodeRequest\022\037\n\nviewerCode\030\010 " +
      "\001(\0132\013.ViewerCode\"\030\n\005Toast\022\017\n\007message\030\001 \001" +
      "(\t\"\023\n\021ViewerCodeRequest\"\032\n\nViewerCode\022\014\n" +
      "\004code\030\001 \001(\t\"A\n\005Vault\022\031\n\005cells\030\001 \003(\0132\n.Va" +
      "ultCell\022\035\n\007players\030\002 \003(\0132\014.VaultPlayer\"U" +
      "\n\013VaultPlayer\022\t\n\001x\030\001 \001(\021\022\t\n\001z\030\002 \001(\021\022\014\n\004u" +
      "uid\030\003 \001(\t\022\025\n\005color\030\004 \001(\0132\006.Color\022\013\n\003yaw\030" +
      "\005 \001(\002\"(\n\005Color\022\t\n\001r\030\001 \001(\r\022\t\n\001g\030\002 \001(\r\022\t\n\001" +
      "b\030\003 \001(\r\"\255\001\n\tVaultCell\022\t\n\001x\030\001 \001(\021\022\t\n\001z\030\002 " +
      "\001(\021\022\033\n\010cellType\030\003 \001(\0162\t.CellType\022\033\n\010room" +
      "Type\030\004 \001(\0162\t.RoomType\022\033\n\010roomName\030\005 \001(\0162" +
      "\t.RoomName\022\020\n\010explored\030\006 \001(\010\022\021\n\tinscribe" +
      "d\030\007 \001(\010\022\016\n\006marked\030\010 \001(\010\" \n\020PlayerDisconn" +
      "ect\022\014\n\004uuid\030\001 \001(\t*\206\001\n\013MessageType\022\t\n\005VAU" +
      "LT\020\000\022\020\n\014VAULT_PLAYER\020\001\022\016\n\nVAULT_CELL\020\002\022\025" +
      "\n\021PLAYER_DISCONNECT\020\003\022\t\n\005TOAST\020\004\022\027\n\023VIEW" +
      "ER_CODE_REQUEST\020\005\022\017\n\013VIEWER_CODE\020\006*a\n\010Ce" +
      "llType\022\024\n\020CELLTYPE_UNKNOWN\020\000\022\021\n\rCELLTYPE" +
      "_ROOM\020\001\022\025\n\021CELLTYPE_TUNNEL_X\020\002\022\025\n\021CELLTY" +
      "PE_TUNNEL_Z\020\003*\206\001\n\010RoomType\022\024\n\020ROOMTYPE_U" +
      "NKNOWN\020\000\022\022\n\016ROOMTYPE_START\020\001\022\022\n\016ROOMTYPE" +
      "_BASIC\020\002\022\020\n\014ROOMTYPE_ORE\020\003\022\026\n\022ROOMTYPE_C" +
      "HALLENGE\020\004\022\022\n\016ROOMTYPE_OMEGA\020\005*\240\004\n\010RoomN" +
      "ame\022\024\n\020ROOMNAME_UNKNOWN\020\000\022\027\n\023ROOMNAME_BL" +
      "ACKSMITH\020\001\022\021\n\rROOMNAME_COVE\020\002\022\032\n\026ROOMNAM" +
      "E_CRYSTAL_CAVES\020\003\022\025\n\021ROOMNAME_DIG_SITE\020\004" +
      "\022\023\n\017ROOMNAME_DRAGON\020\005\022\024\n\020ROOMNAME_FACTOR" +
      "Y\020\006\022\024\n\020ROOMNAME_LIBRARY\020\007\022\021\n\rROOMNAME_MI" +
      "NE\020\010\022\026\n\022ROOMNAME_MUSH_ROOM\020\t\022\025\n\021ROOMNAME" +
      "_PAINTING\020\n\022\023\n\017ROOMNAME_VENDOR\020\013\022\024\n\020ROOM" +
      "NAME_VILLAGE\020\014\022\026\n\022ROOMNAME_WILD_WEST\020\r\022\023" +
      "\n\017ROOMNAME_X_MARK\020\016\022\021\n\rROOMNAME_CUBE\020\017\022\020" +
      "\n\014ROOMNAME_LAB\020\020\022\021\n\rROOMNAME_RAID\020\021\022\030\n\024R" +
      "OOMNAME_PIRATE_CAVE\020\022\022\023\n\017ROOMNAME_GARDEN" +
      "\020\023\022\023\n\017ROOMNAME_ARCADE\020\024\022\022\n\016ROOMNAME_COME" +
      "T\020\025\022\025\n\021ROOMNAME_PLAYZONE\020\026\022\035\n\031ROOMNAME_H" +
      "ELLISH_DIG_SITE\020\027BA\n#com.nodiumhosting.v" +
      "aultmapper.protoB\020VaultMapperProtoP\001Z\006/p" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Type", "Vault", "VaultPlayer", "VaultCell", "PlayerDisconnect", "Toast", "ViewerCodeRequest", "ViewerCode", });
    internal_static_Toast_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Toast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Toast_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ViewerCodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ViewerCodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ViewerCodeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ViewerCode_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ViewerCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ViewerCode_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_Vault_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Vault_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Vault_descriptor,
        new java.lang.String[] { "Cells", "Players", });
    internal_static_VaultPlayer_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_VaultPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VaultPlayer_descriptor,
        new java.lang.String[] { "X", "Z", "Uuid", "Color", "Yaw", });
    internal_static_Color_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Color_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Color_descriptor,
        new java.lang.String[] { "R", "G", "B", });
    internal_static_VaultCell_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_VaultCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VaultCell_descriptor,
        new java.lang.String[] { "X", "Z", "CellType", "RoomType", "RoomName", "Explored", "Inscribed", "Marked", });
    internal_static_PlayerDisconnect_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_PlayerDisconnect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerDisconnect_descriptor,
        new java.lang.String[] { "Uuid", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
