// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vaultmapper.proto
// Protobuf Java Version: 4.29.1

package com.nodiumhosting.vaultmapper.proto;

/**
 * Protobuf type {@code Vault}
 */
public final class Vault extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Vault)
    VaultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Vault.class.getName());
  }
  // Use Vault.newBuilder() to construct.
  private Vault(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Vault() {
    cells_ = java.util.Collections.emptyList();
    players_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Vault_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Vault_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nodiumhosting.vaultmapper.proto.Vault.class, com.nodiumhosting.vaultmapper.proto.Vault.Builder.class);
  }

  public static final int CELLS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.nodiumhosting.vaultmapper.proto.VaultCell> cells_;
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.nodiumhosting.vaultmapper.proto.VaultCell> getCellsList() {
    return cells_;
  }
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder> 
      getCellsOrBuilderList() {
    return cells_;
  }
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  @java.lang.Override
  public int getCellsCount() {
    return cells_.size();
  }
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultCell getCells(int index) {
    return cells_.get(index);
  }
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder getCellsOrBuilder(
      int index) {
    return cells_.get(index);
  }

  public static final int PLAYERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.nodiumhosting.vaultmapper.proto.VaultPlayer> players_;
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.nodiumhosting.vaultmapper.proto.VaultPlayer> getPlayersList() {
    return players_;
  }
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  @java.lang.Override
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultPlayer getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cells_.size(); i++) {
      output.writeMessage(1, cells_.get(i));
    }
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(2, players_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cells_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cells_.get(i));
    }
    for (int i = 0; i < players_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, players_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nodiumhosting.vaultmapper.proto.Vault)) {
      return super.equals(obj);
    }
    com.nodiumhosting.vaultmapper.proto.Vault other = (com.nodiumhosting.vaultmapper.proto.Vault) obj;

    if (!getCellsList()
        .equals(other.getCellsList())) return false;
    if (!getPlayersList()
        .equals(other.getPlayersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCellsCount() > 0) {
      hash = (37 * hash) + CELLS_FIELD_NUMBER;
      hash = (53 * hash) + getCellsList().hashCode();
    }
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nodiumhosting.vaultmapper.proto.Vault parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nodiumhosting.vaultmapper.proto.Vault parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.Vault parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nodiumhosting.vaultmapper.proto.Vault prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Vault}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Vault)
      com.nodiumhosting.vaultmapper.proto.VaultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Vault_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Vault_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nodiumhosting.vaultmapper.proto.Vault.class, com.nodiumhosting.vaultmapper.proto.Vault.Builder.class);
    }

    // Construct using com.nodiumhosting.vaultmapper.proto.Vault.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
      } else {
        cells_ = null;
        cellsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
      } else {
        players_ = null;
        playersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_Vault_descriptor;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.Vault getDefaultInstanceForType() {
      return com.nodiumhosting.vaultmapper.proto.Vault.getDefaultInstance();
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.Vault build() {
      com.nodiumhosting.vaultmapper.proto.Vault result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.Vault buildPartial() {
      com.nodiumhosting.vaultmapper.proto.Vault result = new com.nodiumhosting.vaultmapper.proto.Vault(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.nodiumhosting.vaultmapper.proto.Vault result) {
      if (cellsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cells_ = cells_;
      } else {
        result.cells_ = cellsBuilder_.build();
      }
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
    }

    private void buildPartial0(com.nodiumhosting.vaultmapper.proto.Vault result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nodiumhosting.vaultmapper.proto.Vault) {
        return mergeFrom((com.nodiumhosting.vaultmapper.proto.Vault)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nodiumhosting.vaultmapper.proto.Vault other) {
      if (other == com.nodiumhosting.vaultmapper.proto.Vault.getDefaultInstance()) return this;
      if (cellsBuilder_ == null) {
        if (!other.cells_.isEmpty()) {
          if (cells_.isEmpty()) {
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCellsIsMutable();
            cells_.addAll(other.cells_);
          }
          onChanged();
        }
      } else {
        if (!other.cells_.isEmpty()) {
          if (cellsBuilder_.isEmpty()) {
            cellsBuilder_.dispose();
            cellsBuilder_ = null;
            cells_ = other.cells_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cellsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCellsFieldBuilder() : null;
          } else {
            cellsBuilder_.addAllMessages(other.cells_);
          }
        }
      }
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000002);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.nodiumhosting.vaultmapper.proto.VaultCell m =
                  input.readMessage(
                      com.nodiumhosting.vaultmapper.proto.VaultCell.parser(),
                      extensionRegistry);
              if (cellsBuilder_ == null) {
                ensureCellsIsMutable();
                cells_.add(m);
              } else {
                cellsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              com.nodiumhosting.vaultmapper.proto.VaultPlayer m =
                  input.readMessage(
                      com.nodiumhosting.vaultmapper.proto.VaultPlayer.parser(),
                      extensionRegistry);
              if (playersBuilder_ == null) {
                ensurePlayersIsMutable();
                players_.add(m);
              } else {
                playersBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.nodiumhosting.vaultmapper.proto.VaultCell> cells_ =
      java.util.Collections.emptyList();
    private void ensureCellsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cells_ = new java.util.ArrayList<com.nodiumhosting.vaultmapper.proto.VaultCell>(cells_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultCell, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder, com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder> cellsBuilder_;

    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public java.util.List<com.nodiumhosting.vaultmapper.proto.VaultCell> getCellsList() {
      if (cellsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cells_);
      } else {
        return cellsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public int getCellsCount() {
      if (cellsBuilder_ == null) {
        return cells_.size();
      } else {
        return cellsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCell getCells(int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);
      } else {
        return cellsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder setCells(
        int index, com.nodiumhosting.vaultmapper.proto.VaultCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.set(index, value);
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder setCells(
        int index, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.set(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder addCells(com.nodiumhosting.vaultmapper.proto.VaultCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder addCells(
        int index, com.nodiumhosting.vaultmapper.proto.VaultCell value) {
      if (cellsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCellsIsMutable();
        cells_.add(index, value);
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder addCells(
        com.nodiumhosting.vaultmapper.proto.VaultCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder addCells(
        int index, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder builderForValue) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.add(index, builderForValue.build());
        onChanged();
      } else {
        cellsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder addAllCells(
        java.lang.Iterable<? extends com.nodiumhosting.vaultmapper.proto.VaultCell> values) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cells_);
        onChanged();
      } else {
        cellsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder clearCells() {
      if (cellsBuilder_ == null) {
        cells_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cellsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public Builder removeCells(int index) {
      if (cellsBuilder_ == null) {
        ensureCellsIsMutable();
        cells_.remove(index);
        onChanged();
      } else {
        cellsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCell.Builder getCellsBuilder(
        int index) {
      return getCellsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder getCellsOrBuilder(
        int index) {
      if (cellsBuilder_ == null) {
        return cells_.get(index);  } else {
        return cellsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public java.util.List<? extends com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder> 
         getCellsOrBuilderList() {
      if (cellsBuilder_ != null) {
        return cellsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cells_);
      }
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCell.Builder addCellsBuilder() {
      return getCellsFieldBuilder().addBuilder(
          com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance());
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultCell.Builder addCellsBuilder(
        int index) {
      return getCellsFieldBuilder().addBuilder(
          index, com.nodiumhosting.vaultmapper.proto.VaultCell.getDefaultInstance());
    }
    /**
     * <code>repeated .VaultCell cells = 1;</code>
     */
    public java.util.List<com.nodiumhosting.vaultmapper.proto.VaultCell.Builder> 
         getCellsBuilderList() {
      return getCellsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultCell, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder, com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder> 
        getCellsFieldBuilder() {
      if (cellsBuilder_ == null) {
        cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.VaultCell, com.nodiumhosting.vaultmapper.proto.VaultCell.Builder, com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder>(
                cells_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cells_ = null;
      }
      return cellsBuilder_;
    }

    private java.util.List<com.nodiumhosting.vaultmapper.proto.VaultPlayer> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        players_ = new java.util.ArrayList<com.nodiumhosting.vaultmapper.proto.VaultPlayer>(players_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultPlayer, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder, com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder> playersBuilder_;

    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public java.util.List<com.nodiumhosting.vaultmapper.proto.VaultPlayer> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder setPlayers(
        int index, com.nodiumhosting.vaultmapper.proto.VaultPlayer value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder setPlayers(
        int index, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder addPlayers(com.nodiumhosting.vaultmapper.proto.VaultPlayer value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder addPlayers(
        int index, com.nodiumhosting.vaultmapper.proto.VaultPlayer value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder addPlayers(
        com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder addPlayers(
        int index, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends com.nodiumhosting.vaultmapper.proto.VaultPlayer> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder getPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public java.util.List<? extends com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder addPlayersBuilder() {
      return getPlayersFieldBuilder().addBuilder(
          com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance());
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder addPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().addBuilder(
          index, com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance());
    }
    /**
     * <code>repeated .VaultPlayer players = 2;</code>
     */
    public java.util.List<com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder> 
         getPlayersBuilderList() {
      return getPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.VaultPlayer, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder, com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder> 
        getPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.VaultPlayer, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder, com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder>(
                players_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Vault)
  }

  // @@protoc_insertion_point(class_scope:Vault)
  private static final com.nodiumhosting.vaultmapper.proto.Vault DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nodiumhosting.vaultmapper.proto.Vault();
  }

  public static com.nodiumhosting.vaultmapper.proto.Vault getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Vault>
      PARSER = new com.google.protobuf.AbstractParser<Vault>() {
    @java.lang.Override
    public Vault parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Vault> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Vault> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.Vault getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

