// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.30.1

package com.nodiumhosting.vaultmapper.proto;

/**
 * Protobuf type {@code VaultPlayer}
 */
public final class VaultPlayer extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:VaultPlayer)
    VaultPlayerOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 1,
      /* suffix= */ "",
      VaultPlayer.class.getName());
  }
  // Use VaultPlayer.newBuilder() to construct.
  private VaultPlayer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VaultPlayer() {
    uuid_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultPlayer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultPlayer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nodiumhosting.vaultmapper.proto.VaultPlayer.class, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder.class);
  }

  private int bitField0_;
  public static final int X_FIELD_NUMBER = 1;
  private int x_ = 0;
  /**
   * <code>sint32 x = 1;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Z_FIELD_NUMBER = 2;
  private int z_ = 0;
  /**
   * <code>sint32 z = 2;</code>
   * @return The z.
   */
  @java.lang.Override
  public int getZ() {
    return z_;
  }

  public static final int UUID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uuid_ = "";
  /**
   * <code>string uuid = 3;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 3;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 4;
  private com.nodiumhosting.vaultmapper.proto.Color color_;
  /**
   * <code>.Color color = 4;</code>
   * @return Whether the color field is set.
   */
  @java.lang.Override
  public boolean hasColor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Color color = 4;</code>
   * @return The color.
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.Color getColor() {
    return color_ == null ? com.nodiumhosting.vaultmapper.proto.Color.getDefaultInstance() : color_;
  }
  /**
   * <code>.Color color = 4;</code>
   */
  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.ColorOrBuilder getColorOrBuilder() {
    return color_ == null ? com.nodiumhosting.vaultmapper.proto.Color.getDefaultInstance() : color_;
  }

  public static final int YAW_FIELD_NUMBER = 5;
  private float yaw_ = 0F;
  /**
   * <code>float yaw = 5;</code>
   * @return The yaw.
   */
  @java.lang.Override
  public float getYaw() {
    return yaw_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (x_ != 0) {
      output.writeSInt32(1, x_);
    }
    if (z_ != 0) {
      output.writeSInt32(2, z_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, uuid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getColor());
    }
    if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
      output.writeFloat(5, yaw_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, x_);
    }
    if (z_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(2, z_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, uuid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getColor());
    }
    if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, yaw_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nodiumhosting.vaultmapper.proto.VaultPlayer)) {
      return super.equals(obj);
    }
    com.nodiumhosting.vaultmapper.proto.VaultPlayer other = (com.nodiumhosting.vaultmapper.proto.VaultPlayer) obj;

    if (getX()
        != other.getX()) return false;
    if (getZ()
        != other.getZ()) return false;
    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (hasColor() != other.hasColor()) return false;
    if (hasColor()) {
      if (!getColor()
          .equals(other.getColor())) return false;
    }
    if (java.lang.Float.floatToIntBits(getYaw())
        != java.lang.Float.floatToIntBits(
            other.getYaw())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Z_FIELD_NUMBER;
    hash = (53 * hash) + getZ();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    if (hasColor()) {
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
    }
    hash = (37 * hash) + YAW_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getYaw());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nodiumhosting.vaultmapper.proto.VaultPlayer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VaultPlayer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VaultPlayer)
      com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultPlayer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nodiumhosting.vaultmapper.proto.VaultPlayer.class, com.nodiumhosting.vaultmapper.proto.VaultPlayer.Builder.class);
    }

    // Construct using com.nodiumhosting.vaultmapper.proto.VaultPlayer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetColorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      x_ = 0;
      z_ = 0;
      uuid_ = "";
      color_ = null;
      if (colorBuilder_ != null) {
        colorBuilder_.dispose();
        colorBuilder_ = null;
      }
      yaw_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nodiumhosting.vaultmapper.proto.VaultMapperProto.internal_static_VaultPlayer_descriptor;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer getDefaultInstanceForType() {
      return com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance();
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer build() {
      com.nodiumhosting.vaultmapper.proto.VaultPlayer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nodiumhosting.vaultmapper.proto.VaultPlayer buildPartial() {
      com.nodiumhosting.vaultmapper.proto.VaultPlayer result = new com.nodiumhosting.vaultmapper.proto.VaultPlayer(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nodiumhosting.vaultmapper.proto.VaultPlayer result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.z_ = z_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.uuid_ = uuid_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.color_ = colorBuilder_ == null
            ? color_
            : colorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.yaw_ = yaw_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nodiumhosting.vaultmapper.proto.VaultPlayer) {
        return mergeFrom((com.nodiumhosting.vaultmapper.proto.VaultPlayer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nodiumhosting.vaultmapper.proto.VaultPlayer other) {
      if (other == com.nodiumhosting.vaultmapper.proto.VaultPlayer.getDefaultInstance()) return this;
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getZ() != 0) {
        setZ(other.getZ());
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasColor()) {
        mergeColor(other.getColor());
      }
      if (java.lang.Float.floatToRawIntBits(other.getYaw()) != 0) {
        setYaw(other.getYaw());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              x_ = input.readSInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              z_ = input.readSInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              uuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetColorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 45: {
              yaw_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int x_ ;
    /**
     * <code>sint32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <code>sint32 x = 1;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {

      x_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0;
      onChanged();
      return this;
    }

    private int z_ ;
    /**
     * <code>sint32 z = 2;</code>
     * @return The z.
     */
    @java.lang.Override
    public int getZ() {
      return z_;
    }
    /**
     * <code>sint32 z = 2;</code>
     * @param value The z to set.
     * @return This builder for chaining.
     */
    public Builder setZ(int value) {

      z_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 z = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearZ() {
      bitField0_ = (bitField0_ & ~0x00000002);
      z_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 3;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 3;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 3;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uuid_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      uuid_ = getDefaultInstance().getUuid();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 3;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uuid_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.nodiumhosting.vaultmapper.proto.Color color_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.Color, com.nodiumhosting.vaultmapper.proto.Color.Builder, com.nodiumhosting.vaultmapper.proto.ColorOrBuilder> colorBuilder_;
    /**
     * <code>.Color color = 4;</code>
     * @return Whether the color field is set.
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.Color color = 4;</code>
     * @return The color.
     */
    public com.nodiumhosting.vaultmapper.proto.Color getColor() {
      if (colorBuilder_ == null) {
        return color_ == null ? com.nodiumhosting.vaultmapper.proto.Color.getDefaultInstance() : color_;
      } else {
        return colorBuilder_.getMessage();
      }
    }
    /**
     * <code>.Color color = 4;</code>
     */
    public Builder setColor(com.nodiumhosting.vaultmapper.proto.Color value) {
      if (colorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        color_ = value;
      } else {
        colorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Color color = 4;</code>
     */
    public Builder setColor(
        com.nodiumhosting.vaultmapper.proto.Color.Builder builderForValue) {
      if (colorBuilder_ == null) {
        color_ = builderForValue.build();
      } else {
        colorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Color color = 4;</code>
     */
    public Builder mergeColor(com.nodiumhosting.vaultmapper.proto.Color value) {
      if (colorBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          color_ != null &&
          color_ != com.nodiumhosting.vaultmapper.proto.Color.getDefaultInstance()) {
          getColorBuilder().mergeFrom(value);
        } else {
          color_ = value;
        }
      } else {
        colorBuilder_.mergeFrom(value);
      }
      if (color_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Color color = 4;</code>
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000008);
      color_ = null;
      if (colorBuilder_ != null) {
        colorBuilder_.dispose();
        colorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Color color = 4;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.Color.Builder getColorBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.Color color = 4;</code>
     */
    public com.nodiumhosting.vaultmapper.proto.ColorOrBuilder getColorOrBuilder() {
      if (colorBuilder_ != null) {
        return colorBuilder_.getMessageOrBuilder();
      } else {
        return color_ == null ?
            com.nodiumhosting.vaultmapper.proto.Color.getDefaultInstance() : color_;
      }
    }
    /**
     * <code>.Color color = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nodiumhosting.vaultmapper.proto.Color, com.nodiumhosting.vaultmapper.proto.Color.Builder, com.nodiumhosting.vaultmapper.proto.ColorOrBuilder> 
        internalGetColorFieldBuilder() {
      if (colorBuilder_ == null) {
        colorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nodiumhosting.vaultmapper.proto.Color, com.nodiumhosting.vaultmapper.proto.Color.Builder, com.nodiumhosting.vaultmapper.proto.ColorOrBuilder>(
                getColor(),
                getParentForChildren(),
                isClean());
        color_ = null;
      }
      return colorBuilder_;
    }

    private float yaw_ ;
    /**
     * <code>float yaw = 5;</code>
     * @return The yaw.
     */
    @java.lang.Override
    public float getYaw() {
      return yaw_;
    }
    /**
     * <code>float yaw = 5;</code>
     * @param value The yaw to set.
     * @return This builder for chaining.
     */
    public Builder setYaw(float value) {

      yaw_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float yaw = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearYaw() {
      bitField0_ = (bitField0_ & ~0x00000010);
      yaw_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:VaultPlayer)
  }

  // @@protoc_insertion_point(class_scope:VaultPlayer)
  private static final com.nodiumhosting.vaultmapper.proto.VaultPlayer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nodiumhosting.vaultmapper.proto.VaultPlayer();
  }

  public static com.nodiumhosting.vaultmapper.proto.VaultPlayer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VaultPlayer>
      PARSER = new com.google.protobuf.AbstractParser<VaultPlayer>() {
    @java.lang.Override
    public VaultPlayer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VaultPlayer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VaultPlayer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nodiumhosting.vaultmapper.proto.VaultPlayer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

