// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.28.3

package com.nodiumhosting.vaultmapper.proto;

public interface VaultPlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VaultPlayer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>sint32 z = 2;</code>
   * @return The z.
   */
  int getZ();

  /**
   * <code>string uuid = 3;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 3;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>.Color color = 4;</code>
   * @return Whether the color field is set.
   */
  boolean hasColor();
  /**
   * <code>.Color color = 4;</code>
   * @return The color.
   */
  com.nodiumhosting.vaultmapper.proto.Color getColor();
  /**
   * <code>.Color color = 4;</code>
   */
  com.nodiumhosting.vaultmapper.proto.ColorOrBuilder getColorOrBuilder();

  /**
   * <code>float yaw = 5;</code>
   * @return The yaw.
   */
  float getYaw();
}
