// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.29.1

package com.nodiumhosting.vaultmapper.proto;

public interface VaultCellOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VaultCell)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>sint32 z = 2;</code>
   * @return The z.
   */
  int getZ();

  /**
   * <code>.CellType cellType = 3;</code>
   * @return The enum numeric value on the wire for cellType.
   */
  int getCellTypeValue();
  /**
   * <code>.CellType cellType = 3;</code>
   * @return The cellType.
   */
  com.nodiumhosting.vaultmapper.proto.CellType getCellType();

  /**
   * <code>.RoomType roomType = 4;</code>
   * @return The enum numeric value on the wire for roomType.
   */
  int getRoomTypeValue();
  /**
   * <code>.RoomType roomType = 4;</code>
   * @return The roomType.
   */
  com.nodiumhosting.vaultmapper.proto.RoomType getRoomType();

  /**
   * <code>.RoomName roomName = 5;</code>
   * @return The enum numeric value on the wire for roomName.
   */
  int getRoomNameValue();
  /**
   * <code>.RoomName roomName = 5;</code>
   * @return The roomName.
   */
  com.nodiumhosting.vaultmapper.proto.RoomName getRoomName();

  /**
   * <code>bool explored = 6;</code>
   * @return The explored.
   */
  boolean getExplored();

  /**
   * <code>bool inscribed = 7;</code>
   * @return The inscribed.
   */
  boolean getInscribed();

  /**
   * <code>bool marked = 8;</code>
   * @return The marked.
   */
  boolean getMarked();
}
