// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.30.1

package com.nodiumhosting.vaultmapper.proto;

public interface VaultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vault)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  java.util.List<com.nodiumhosting.vaultmapper.proto.VaultCell> 
      getCellsList();
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  com.nodiumhosting.vaultmapper.proto.VaultCell getCells(int index);
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  int getCellsCount();
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  java.util.List<? extends com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder> 
      getCellsOrBuilderList();
  /**
   * <code>repeated .VaultCell cells = 1;</code>
   */
  com.nodiumhosting.vaultmapper.proto.VaultCellOrBuilder getCellsOrBuilder(
      int index);

  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  java.util.List<com.nodiumhosting.vaultmapper.proto.VaultPlayer> 
      getPlayersList();
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  com.nodiumhosting.vaultmapper.proto.VaultPlayer getPlayers(int index);
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  java.util.List<? extends com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .VaultPlayer players = 2;</code>
   */
  com.nodiumhosting.vaultmapper.proto.VaultPlayerOrBuilder getPlayersOrBuilder(
      int index);
}
