// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VaultMapperProtocol/vaultmapper.proto
// Protobuf Java Version: 4.28.3

package com.nodiumhosting.vaultmapper.proto;

public interface ViewerCodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ViewerCodeRequest)
    com.google.protobuf.MessageOrBuilder {
}
