modLoader="javafml"
loaderVersion="[40,)"
license="AGPL-3.0"
issueTrackerURL="https://github.com/NodiumHosting/VaultMapper/issues"
[[mods]]
modId="vaultmapper"
version="${file.jarVersion}"
displayName="VaultMapper"
displayURL="https://nodiumhosting.com/"
logoFile="icon.png"
credits="NodiumHosting.com"
authors="NodiumHosting.com"
description='''
A mod that allows you to map vaults in the Vault Hunters modpack.
'''