name: Build and upload jar to release

github-token:
  permissions:
    contents: write
    contents-reason: change release assets (upload jar)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build mod
        run: ./gradlew build
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "build/libs/*.jar"
          repo-token: ${{ secrets.GITHUB_TOKEN }}